---
# author by: Tommy
- name: unarchive MySQL package
  unarchive: src={{ mysql_file_path }} dest={{ software_files_path }} owner=root group=root copy=no mode=0755
- name: Configuration MySQL
  shell: chdir={{ software_files_path }}/mysql-{{ mysql_version }} {{ mysql_configure_arg }}
- name: make MySQL
  shell: chdir={{ software_files_path }}/mysql-{{ mysql_version }} make
- name: make install MySQL 
  shell: chdir={{ software_files_path }}/mysql-{{ mysql_version }}  make install
